server:
  port: 8081

spring:
#  datasource:
#    username: root
#    password: Muathu@123
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/source-base
#  jpa:
#    hibernate:
#      ddl-auto: update
#    generate-ddl: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
  application:
    name: USER-SERVICE

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8888/eureka/